language: c
compiler: clang
os: osx
matrix:
  include:
  # Sierra
  - osx_image: xcode9.2
  # El Capitan
  - osx_image: xcode8
cache:
  directories:
  - "$HOME/.gem/ruby"
  - Library/Homebrew/vendor/bundle
before_install:
- sudo chown -R "$USER" "$(brew --repo)"
- travis_retry brew update
- HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
- mkdir -p "$HOMEBREW_TAP_DIR"
- rm -rf "$HOMEBREW_TAP_DIR"
- ln -s "$PWD" "$HOMEBREW_TAP_DIR"
# - rm /usr/local/bin/tox
# - rm /usr/local/bin/tox-quickstart
script:
- brew audit --online --strict amancevice/tap/brewcleaner
- brew audit --online --strict amancevice/tap/dip
- brew audit --online --strict amancevice/tap/poet
# - brew audit --online --strict amancevice/tap/tox
- brew install --build-bottle amancevice/tap/brewcleaner
- brew install --build-bottle amancevice/tap/dip
- brew install --build-bottle amancevice/tap/poet
# - brew install --build-bottle amancevice/tap/tox
- brew bottle --no-rebuild amancevice/tap/brewcleaner
- brew bottle --no-rebuild amancevice/tap/dip
- brew bottle --no-rebuild amancevice/tap/poet
# - brew bottle --no-rebuild amancevice/tap/tox
deploy:
- provider: releases
  api_key:
    secure: 1SuwEiiQpnHVFwgNwTHSOeL7UgSNk4B3rwflpj8wfjkavVBGMeVj7wHJJuOga3201XK4mk9FYB9KYXrCxXk4j/wz9JVcdDZG/9Q4Omw2uIKtfTGR98+/xXw2JK8pPmphoBg/9YDaAo207iwj4vf1E20ohWkqeGktMCw4KLmIdlKxOEdUlI/0uvhYCyspnFFrMsxq25HhEksWNJEHulhFe2+48kFpG2TK9boQZBf0I9vCXDP739nudtzVBRI2yO2iv9yU/eRWGFXHbg43rM2fLXEJnhxXcbu1E8mH6JWQ2m86QAnsgB/A2oEAS4ubRIMrb4/XV14bsxmG/xNvt1ivBCA56azY1yU/hJdpJQvSnx/K0MJSOO508Pn6zcmeCccy1F77a8IsIIp3jUJEjW64TBzCKSAq2fcUQVcbx9MIouWaN9iptVVdOnGL+LW3GrkHs7aRSjy45fpEb09oD/1/88W9Wj/34ryJbgt+SzeJoDmGKb8fGsVKfyV0bho3CEMUFxmYTSAIQegvjNrqezkyOwekjhUBzXXPjNgELg/EisVkpqDUx57Y7e40Y+Gez7wpO4m3RJxRBk89dqx3F9BIPXLZJ4UXWrfvxbz7hLE1mc7hsEi4jT3x4jQ7JhnzbE6NIq9st5JfmhiesHmHsMuK7DYlMx4MNoVk+Y6T9suHcxU=
  file: ${TRAVIS_TAG}.*.bottle*.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: amancevice/homebrew-tap
    tags: true
