language: objective-c

matrix:
  include:
  - osx_image: xcode11
    env:
    - FORMULA=dip
  - osx_image: xcode10.3
    env:
    - FORMULA=dip
  - osx_image: xcode9.4
    env:
    - FORMULA=dip
  - osx_image: xcode11
    env:
    - FORMULA=brewcleaner
  - osx_image: xcode10.3
    env:
    - FORMULA=brewcleaner
  - osx_image: xcode9.4
    env:
    - FORMULA=brewcleaner

before_install:
- brew update

script:
- brew audit --online --strict "amancevice/tap/${FORMULA}"
- brew install --build-bottle "amancevice/tap/${FORMULA}"
- brew bottle --no-rebuild "amancevice/tap/${FORMULA}"

before_deploy:
- for file in $(find . -name "*.bottle*.tar.gz"); do mv ${file} $(echo ${file} | sed s/--/-/); done

deploy:
- provider: releases
  api_key:
    secure: >
      1SuwEiiQpnHVFwgNwTHSOeL7UgSNk4B3rwflpj8wfjkavVBGMeVj7wHJJuOga3201XK4mk9FY
      B9KYXrCxXk4j/wz9JVcdDZG/9Q4Omw2uIKtfTGR98+/xXw2JK8pPmphoBg/9YDaAo207iwj4v
      f1E20ohWkqeGktMCw4KLmIdlKxOEdUlI/0uvhYCyspnFFrMsxq25HhEksWNJEHulhFe2+48kF
      pG2TK9boQZBf0I9vCXDP739nudtzVBRI2yO2iv9yU/eRWGFXHbg43rM2fLXEJnhxXcbu1E8mH
      6JWQ2m86QAnsgB/A2oEAS4ubRIMrb4/XV14bsxmG/xNvt1ivBCA56azY1yU/hJdpJQvSnx/K0
      MJSOO508Pn6zcmeCccy1F77a8IsIIp3jUJEjW64TBzCKSAq2fcUQVcbx9MIouWaN9iptVVdOn
      GL+LW3GrkHs7aRSjy45fpEb09oD/1/88W9Wj/34ryJbgt+SzeJoDmGKb8fGsVKfyV0bho3CEM
      UFxmYTSAIQegvjNrqezkyOwekjhUBzXXPjNgELg/EisVkpqDUx57Y7e40Y+Gez7wpO4m3RJxR
      Bk89dqx3F9BIPXLZJ4UXWrfvxbz7hLE1mc7hsEi4jT3x4jQ7JhnzbE6NIq9st5JfmhiesHmHs
      MuK7DYlMx4MNoVk+Y6T9suHcxU=
  file_glob: true
  file: ${TRAVIS_TAG}.*.bottle*.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: amancevice/homebrew-tap
    tags: true
