name: bottle
on:
  pull_request:
  push:
jobs:
  dip:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: homebrew
          path: /usr/local/Homebrew/Library
      - uses: ./.github/actions/install-brew
      - uses: ./.github/actions/audit
        with: { formula: dip }
  shenv:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: homebrew
          path: /usr/local/Homebrew/Library
      - uses: ./.github/actions/install-brew
      - uses: ./.github/actions/audit
        with: { formula: shenv }
