name: shenv
on:
  pull_request:
    paths:
      - Formula/shenv.rb
  push:
    paths:
      - Formula/shenv.rb
jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: homebrew
          path: /usr/local/Homebrew/Library
      - uses: ./.github/actions/install-brew
      - uses: ./.github/actions/audit
        with:
          formula: shenv
